### ISSUE TITLE
The parser failed to parse this JSON 

### ISSUE THREAD

**Issue by oney** [promplate/partial-json-parser-js#1]
Thanks for making this package! It's very useful.

I encounter an issue. My LLM generates this weird but valid JSON string
```
[
{
"yy": {
"message": "yy"
											,
"yy": "yy"
}
},
{
"xx": {
"xx": "xx"
}
}]
```
Native `JSON.parse(str)` can parse it successfully with
```json
[{"yy":{"message":"yy","yy":"yy"}},{"xx":{"xx":"xx"}}]
```

But `import { parse } from "partial-json"; parse(str);` output
```json
[{"yy":{"message":"yy"}}]
```

Could you help me?

**Comment by CNSeniorious000** [comment]
Thanks a lot for providing this! I will take a look

**Comment by CNSeniorious000** [comment]
I see. It seems I forgot `\t` is a valid space char in JSON. I will make a new release solving this soon.

**Comment by CNSeniorious000** [comment]
Fixed this in [0.1.4](https://www.npmjs.com/package/partial-json/v/0.1.4). Thank you again for trying this package and providing valuable bug.

**Comment by CNSeniorious000** [comment]
Sorry about that, I personally am not familiar with JavaScript packaging so I made a few mistake. I am working on it now

**Comment by CNSeniorious000** [comment]
Fine. I've upload a new version. [v0.1.5](https://www.npmjs.com/package/partial-json/v/0.1.5) solved this. Thank you a lot for reporting this!
