### ISSUE TITLE
Allow partials strings

### ISSUE THREAD

**Issue by thgh** [promplate/partial-json-parser-js#7]
It would be cool to parse it like this: (for AI completions)

```
in:  { "name": { "first": "ind", "last": "go

out: { "name": { "first": "ind", "last": "go" } }
```

**Comment by CNSeniorious000** [comment]
Yeah, but I think it is implemented now, you can use `JSON.stringify(parse(text))` to get the completed JSON as string.

Of course the spaces inside is not preserved. Do you mean that? Or I don't get the difference.

**Comment by thgh** [comment]
Hi, sorry! I thought this repo was related to https://www.npmjs.com/package/partial-json-parser which documents that unclosed strings are considered undefined.

I used this project and it works perfect for the LLM case :-) Thanks!
